PORT = 9090

# Database configuration
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "socyads_db"
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_SSL = false

# Auth
AUTH_DISABLE = true
JWT_ISSUER = "socyads"
JWT_AUDIENCE = "socyads_frontend"
JWT_SECRET = "change-me-in-prod"


